# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10MVMdrhUKaof_SO2ylYIGBXsKeo3IMZw
"""

import keras
import numpy as np

digits = keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = digits.load_data()

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

plt.matshow(x_train[4])

x_train=x_train/255
x_test=x_test/255

x_train.shape

from keras.models import Sequential
from keras.layers import Dense, Activation,Flatten

model=Sequential()

model.add(Flatten(input_shape=[28,28]))
model.add(Dense(20,activation='relu'))
model.add(Dense(10,activation='softmax'))

model.compile(loss="sparse_categorical_crossentropy",optimizer="adam" ,metrics=["accuracy"])

model.fit(x_train,y_train)

p=model.predict(x_test)

p[123]

np.argmax(p[5])

plt.matshow(x_test[5])